services:
  backend:
    image: node:lts
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    command: sh -c "npm install && npx prisma generate && npx prisma db push && npm run dev"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  frontend:
    image: node:lts
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    environment:
      - VITE_API_URL=http://backend:5000
      - PLAYWRIGHT_BASE_URL=http://localhost:5173
    depends_on:
      backend:
        condition: service_healthy

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: hruser
      POSTGRES_PASSWORD: hrpass
      POSTGRES_DB: hrapp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U hruser -d hrapp -h localhost || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: {}
