export const ROLES = {
  ADMIN: 'ADMIN',
  EDITOR: 'EDITOR',
};

export const PERMISSIONS = {
  MANAGE_USERS: 'MANAGE_USERS',
  VIEW_REPORTS: 'VIEW_REPORTS',
  EDIT_SETTINGS: 'EDIT_SETTINGS',
  VIEW_USERS: 'VIEW_USERS',
  MANAGE_ADMINS: 'MANAGE_ADMINS',
  MANAGE_ROLES: 'MANAGE_ROLES',
};
