name: CI

on:
  pull_request:
    branches: [main]

jobs:
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    env:
      REFRESH_TOKEN_SECRET: super-secret-refresh-token
      ACCESS_TOKEN_SECRET: super-secret-access-token

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          cache-dependency-path: backend/package.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./backend

      - name: Run tests
        run: npm test
        working-directory: ./backend

  # frontend-tests:
  #   name: Frontend Tests
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         cache: "npm"
  #         cache-dependency-path: frontend/package.json

  #     - name: Install dependencies
  #       run: npm ci
  #       working-directory: ./frontend

  #     - name: Run tests
  #       run: npm test -- --passWithNoTests
  #       working-directory: ./frontend
