name: Playwright Tests

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24.0.2
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose -f docker-compose.yml up --build -d

      - name: Wait for services
        run: |
          echo "Waiting for backend health check..."
          timeout 60s bash -c 'until curl -s http://localhost:3001/health; do sleep 2; done'

      - name: Run Playwright tests
        run: docker compose exec frontend npm run test:e2e

      - name: Shutdown Docker Compose
        if: always()
        run: docker compose down --volumes
